spring:
  profiles:
    active: prod 
  mail:
    host: smtp.gmail.com       
    port: 587
    username: ${provide-gmail-here}
    password: ${provide-password-here}   # Please dont share 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

           
  
        
        
jwt:
  secret: "z9F!2xBv@pQ7kL%uH#4tM1sN&dR6jW^yG*eC8aV0bXqZ3rT"
  expirationMs: 9000000 # 15 minutes
  refreshExpirationMs: 604800000 # 7 days

logging:
  level:
    com.example.jwtprofiles: DEBUG

google:
  client:
    id: ${provide-your-id-here}  # Please dont share 
    secret: ${provide-your-secret-here}   # Please dont share 
  redirect:
    uri: ${http://localhost:4200/login/google/callback}
